### ISSUE TITLE
asymmetric cryptography

### ISSUE THREAD

**Issue by Mahsa-Bastankhah** [Zokrates/ZoKrates#321] opened 2019-04-12 07:57 UTC
Hi.I'm searching for a ZKP package that supports asymmetric encryption so I can implement following scenario :
Carol encrypts message m with Alice's public key and sends the "cipher text" to Alice. Bob and Alice both know "hash(m)" But because "m" is encrypted by Alice's public key Bob doesn't know "m" and just Alice knows that. Here is the part that needs ZKP : Alice wants to prove Bob that this "cipher text" is actually encrypted of a message which its hash is equal to "hash(m)".
does zokrates supports this?if not does exist any other package that can help me?

**Comment by eupn** [comment] 2019-04-14 21:20
With ZKP can prove the knowledge of `h = hash(m)` preimage (`m`) without revealing the preimage itself. It's sufficient to build a proof for a calculation of SHA-256's or any other hash-function's R1CS with `m` as its secret input.

**Comment by Mahsa-Bastankhah** [comment] 2019-04-15 04:53
I know but what about encryption? to implement the above scenario I need encryption in Zokrates

**Comment by Schaeff** [comment] 2019-04-15 08:07
I'm going to close this as it's a duplicate of #276. Please refer to the discussion there and feel free to reopen if I missed something!

**Closed by Schaeff** 2019-04-15 08:07 UTC
