### ISSUE TITLE
Use different file extension for human readable circuit file 

### ISSUE THREAD

**Issue by stefandeml** [Zokrates/ZoKrates#249] opened 2019-01-31 12:57 UTC
Compiling Zokrates DSL creates a human readable circuit file `out.code`.
Currently this file has the same file extension as the input ZoKrates DSL code. 

To mitigate the `light` flag can be set to suppress creation of the file: `./zokrates compile -i  filename.code --light`

**Comment by petscheit** [comment] 2019-04-24 07:49
Should the out.code file be changed to a .txt file or do you have any other format in mind?

**Comment by Schaeff** [comment] 2019-07-05 23:04
Duplicate of #392

**Closed by Schaeff** 2019-07-05 23:04 UTC
Labels: Good First Issue, Priority: Low, Type: Enhancement
