### ISSUE TITLE
Printing values to debug ! 

### ISSUE THREAD

**Issue by SyedMuhamadYasir** [Zokrates/ZoKrates#1164] opened 2022-06-08 23:41 UTC
## Abstract
Lack of debugging ability, no print statement

## Motivation

A sophisticated toolbox like Zokrates desperately requires a print functionality to ensure that we can see what is going on inside te code ! Please consider this !

**Comment by Schaeff** [comment] 2022-06-28 10:05
Duplicate of #841 fixed in #1171

**Closed as completed by Schaeff** 2022-06-28 10:05 UTC
