### ISSUE TITLE
Very volative 'unwrap on a none value' problem

### ISSUE THREAD

**Issue by m1cm1c** [Zokrates/ZoKrates#978] opened 2021-08-23 16:56 UTC
## Description
I apologize for the long code. I tried removing as much code as possible while preserving the bug.

However, the removal of various individual lines causes the bug to disappear. E.g. removing `q1 = q1 + u64_to_field(y[i])*(u32_to_field(ci)**i)` (despite `q1` being completely unused and that line being equivalent in virtually any way to the line above which would remain unchanged) eliminates the bug. But you can also get rid of it by removing the call to `assert()`, by removing the entirely empty loop, or changing the value of `n`.

## Environment

- Compiler version: ZoKrates 0.7.6
- Operating system: Manjaro

## Steps to Reproduce
Paste this into a file named `bug.zok`:

```zokrates
import "utils/casts/u32_to_field" as u32_to_field
import "utils/casts/u64_to_field" as u64_to_field
import "utils/casts/field_to_u64" as field_to_u64

def verifyMul<N>(u64[N] x, u64[N] y, u64[N] z0, u64[N] z1) -> bool:
	for u32 ci in 1..(2*N) do
		field q0 = 0
		field q1 = 0

		for u32 i in 0..N do
			q0 = q0 + u64_to_field(x[i])*(u32_to_field(ci)**i)
			q1 = q1 + u64_to_field(y[i])*(u32_to_field(ci)**i)
		endfor
	endfor

	return true

const u32 n = 2
const u32 nTimes64Plus1 = n*64 + 1

def expmod<N>(u64[N] base, u64[N] power, u64[N] modulo, u64[nTimes64Plus1][2][N] multiplicativeWitnesses) -> u64[N]:
    bool[N*64] powerBits = [false; N*64]
    for u32 i in 0..N do
        for u32 j in 0..64 do
        endfor
    endfor

    u64[N] y = [...[0; N-1], 1]

	assert(verifyMul(base, y, multiplicativeWitnesses[N*64][0], [0; N]))
    return multiplicativeWitnesses[N*64][0]


def main(u64[n] a, u64[n] b, u64[n] modulo, u64[nTimes64Plus1][2][n] multiplicativeWitnesses) -> u64[n]:
	return expmod(a, b, modulo, multiplicativeWitnesses)
```

Compile:
```
$ zokrates compile -i bug.zok
Compiling bug.zok

called `Option::unwrap()` on a `None` value (/home/circleci/project/zokrates_core/src/static_analysis/propagation.rs:994:38)
This is unexpected, please submit a full bug report at https://github.com/Zokrates/ZoKrates/issues
```

**Comment by dark64** [comment] 2021-08-26 14:21
Hey @m1cm1c, thanks for the report! I got it down to this:

```zok
def func<N>() -> bool:
    // will compile if this for loop is commented out
    for u32 i in 0..N do
    endfor

    u64[N] y = [...[0; N-1], 1]
    u64 q = 0

    for u32 i in 0..N do
        q = y[i] // fails trying to access `y[i]`
    endfor

    return true

def main():
    assert(func::<2>())
    return
````

**Comment by Schaeff** [comment] 2021-08-30 08:49
Thanks a lot for this @m1cm1c, closing this as a duplicate of #981 after some investigation

**Closed as completed by Schaeff** 2021-08-30 08:49 UTC
Labels: Type: Bug, Duplicate
